### ISSUE TITLE
Use the Spotify lyrics source with non-spotify music players

### ISSUE THREAD

**Issue by Tamriel** [IllusionMan1212/lyrics-grabbr#10]
LyricsGrabbr says the Spotify source works only when playing with the Spotify player. I guess this is because it gets the lyrics by spotify track id. It would be great if it would work with other android music players, e.g. by performing a spotify search by song name.

**Comment by IllusionMan1212** [comment]
Copying my reply from the closed issue.

>Performing a name search would be very spotty I think, I'd much rather keep the spotify feature for when using the spotify player only and do the lookup for non-spotify using geniURL.
