### ISSUE TITLE
(Feature request) 1. Keep the screen on in the Lyrics page 2. Pull down to refresh results

### ISSUE THREAD

**Issue by Teliang** [IllusionMan1212/lyrics-grabbr#11]
I enjoy using this app every day, and I think it would be even better with these features:

1. Keep the screen on in the Lyrics page: 
When I am looking at the lyrics for a long time, the screen automatically turns off. I have to touch the screen to keep it on.

2. Pull down to refresh results: 
Sometimes, when the song changes to the next one, the result list still shows the previous song's results. I have to close and restart the app to refresh the results.

**Comment by IllusionMan1212** [comment]
Glad to hear you're enjoying the app :)

I think point 1 can be addressed by having a settings option for that (since keeping the screen on is a bit of a battery drainer)
Point 2 sounds like a bug. I will try to address that and maybe also add pull to refresh in case the bug still happens in rare cases.

**Comment by IllusionMan1212** [comment]
Just merged some code that adds the option to keep the screen on when reading the lyrics.

I haven't added pull to refresh but I tried to fix the issue you're getting with the app showing stale results, please reopen the issue and let me know if you're still encountering that bug.

I think I will make a release soon and that should land in f-droid within a week of the release.

**Comment by Teliang** [comment]
Thank you for adding the option to keep the screen on! 🎉

This bug seems to occur in rare cases. I have not encountered it recently, but if it appears again, I will reopen the issue.

Thanks for the updates and your hard work!
