### ISSUE TITLE
com/spotify/sdk is not FOSS

### ISSUE THREAD

**Issue by licaon-kter** [IllusionMan1212/lyrics-grabbr#12]
as https://github.com/spotify/android-sdk/tree/master has no source code

ref: https://github.com/IllusionMan1212/lyrics-grabbr/blob/v1.0.0/app/build.gradle.kts#L129

-> https://github.com/adamint/spotify-web-api-kotlin/blob/v4.0.2/src/androidMain/kotlin/com/adamratzman/spotify/auth/implicit/SpotifyImplicitLoginActivity.kt#L13

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/issues/3306#note_1989891617

```
\--- com.adamratzman:spotify-api-kotlin-core:4.0.2
     \--- com.adamratzman:spotify-api-kotlin-android:4.0.2
          +--- com.spotify.android:auth:1.2.5
```

**Comment by IllusionMan1212** [comment]
I assume for the app to be reinstated in f-droid I'd have to completely remove the spotify SDK and a simple "This app uses non-free features" is not enough?

**Comment by licaon-kter** [comment]
Yes, at least for the version in F-Droid, eg. Make a gradle flavor without that sdk

**Comment by IllusionMan1212** [comment]
The spotify sdk has been removed in #13 . I will let you know when I create a new release so the app can resume being hosted on f-droid.

**Comment by IllusionMan1212** [comment]
New release is out https://github.com/IllusionMan1212/lyrics-grabbr/releases/tag/v1.1.0
From this release on out spotify shouldn't be an issue.

I would appreciate it if you could reinstate the app.
