### ISSUE TITLE
Add reliable lyrics source

### ISSUE THREAD

**Issue by Tamriel** [IllusionMan1212/lyrics-grabbr#3]
The curren source finds only few songs.
Fetching the lyrics from Spotify seems good. Code can be borrowed from here: https://github.com/lyricstify/lyricstify

**Comment by IllusionMan1212** [comment]
Lyricstify uses the user's own spotify client id/secret to retrieve the lyrics which some people might not want to provide (although this can be made opt-in for users such as yourself)

Lyrics grabbr uses Genius to search for and fetch the lyrics using the provided artist name and song title, and I usually find spotify's naming to work well enough with Genius' naming 

I might look into this soon and check the feasibility of it.
Are you also interested in the synchronization aspect of the spotify API?

**Comment by Tamriel** [comment]
Thank you very much :)
No need for synchronization for me, I just want reliable lyrics.

**Comment by Tamriel** [comment]
When I add the spotify ID and login in spotify, the website "accounts.spotify.com" opens and simply says "invalid client: invalid redirect URI". What should the Redirect URI be set to?

**Comment by Tamriel** [comment]
LyricsGrabbr says this feature works only when playing with the Spotify player. I guess this is because it gets the lyrics by spotify track id. Would it be possible to make this compatible with other android music players by performing a spotify search by song name?

**Comment by IllusionMan1212** [comment]
> What should the Redirect URI be set to?

The URI should be set to `lyricsgrabbr://spotify-auth`

> LyricsGrabbr says this feature works only when playing with the Spotify player. I guess this is because it gets the lyrics by spotify track id. Would it be possible to make this compatible with other android music players by performing a spotify search by song name?

Performing a name search would be very spotty I think, I'd much rather keep the spotify feature for when using the spotify player only and do the lookup for non-spotify using geniURL.


Sorry for the very late reply.

**Comment by Tamriel** [comment]
> > LyricsGrabbr says this feature works only when playing with the Spotify player. I guess this is because it gets the lyrics by spotify track id. Would it be possible to make this compatible with other android music players by performing a spotify search by song name?
> 
> Performing a name search would be very spotty I think, I'd much rather keep the spotify feature for when using the spotify player only and do the lookup for non-spotify using geniURL.

So you propose using Genius instead of Spotify for other Android Music Players, right?
Even though geniURL may be more precise than Spotifys search-by-name, the Genius search results are far worse. I would still greatly prefer Spotify and search-by-name. If you search by track, artists and album it should be precise enough I think.

In the end it's just a wish from me and you can of course decide to keep your software as it is. Thanks for coding so far and sharing it! If I have time in a year maybe I'll code it.

**Comment by IllusionMan1212** [comment]
Well I don't know if you've seen the newest v1.1.0 update but that completely removes spotify as a lyrics source. Using the spotify SDK was against f-droid's terms (and FOSS in general) and I ultimately decided it's not worth it to do different builds.
geniURL is obviously not perfect but it is FOSS and easily self-hostable and I'm sticking with that for the foreseeable future.
